#!/bin/sh

NAME=${NAME:-'go'}
VERSION=${VERSION:-'1.8'}
TAG=${TAG:-go${VERSION}}

ORIGIN_HOST=${ORIGIN_HOST='go.googlesource.com'}
ORIGIN_PATH=${ORIGIN_PATH='go'}

. /package/unpackage/include/common

GOROOT_BOOTSTRAP=${GOROOT_BOOTSTRAP:-${PACKAGE_ROOT}/${NAME}}
GOROOT_FINAL=${GOROOT_FINAL:-${PACKAGE_DIR}}

build() {
    cd ${WORKING}/src || exit 111
    env \
        GOROOT_BOOTSTRAP="${GOROOT_BOOTSTRAP}" \
        GOROOT_FINAL="${GOROOT_FINAL}" \
        ${WORKING}/src/make.bash
}

install() {
    mkdir -p ${PACKAGE_DIR} || exit 111
    tar cf - -C ${WORKING} . | tar xf - -C ${PACKAGE_DIR}
}

entrypoint ${@:-}
