#!/bin/sh

NAME=${NAME:-'heirloom-sh'}
VERSION=${VERSION:-'master'}
ORIGIN_PATH=${ORIGIN_PATH='eunuchs/heirloom-project'}

. /package/unpkg/include/common

if test -d /usr/xpg4/bin
then
    PATH=/usr/xpg4/bin:${PATH}
    export PATH
fi

_configure() {
    cd ${SOURCE}/heirloom/heirloom-sh || exit 111
    pwd
    awk -f /package/unpkg/data/support/heirloom-sh/configure.awk \
        -F = \
        -v BINDIR=${BINDIR} \
        -v MANDIR=${MANDIR} \
        -v INSTALL=${INSTALL} \
        -v STRIP=${STRIP} \
        -v CFLAGS="${CFLAGS}" \
        makefile > makefile.fixed && mv makefile.fixed makefile
}

_main ${@:-}
