#!/bin/sh

NAME=${NAME:-'lz4'}
VERSION=${VERSION:-'1.7.5'}
TAG=${TAG:-v${VERSION}}
ORIGIN_PATH=${ORIGIN_PATH='lz4/lz4'}

. /package/unpkg/include/common

_build() {
    _clean && _make -C lib && _make -C programs
}

_install() {
    _make -C lib install && _make -C programs install
}

_main ${@:-}
