#!/bin/sh

NAME=${NAME:-'unpkg'}
VERSION=${VERSION:-'develop'}
ORIGIN_PATH=${ORIGIN_PATH='colstrom/unpkg'}
TRUNK=${TRUNK:-'develop'}

. ${INCLUDE}/functions

_build() {
    true
}

_install() {
    true
}

_activate() {
    ln -s ${SOURCE} ${PACKAGE_ROOT}/${NAME}
}

_main ${@:-}
