#!/bin/sh

NAME=${NAME:-'unpkg'}
VERSION=${VERSION:-'develop'}
ORIGIN_PATH=${ORIGIN_PATH='colstrom/unpkg'}
TRUNK=${TRUNK:-'develop'}

. /package/unpkg/include/common

_build() {
    true
}

_install() {
    mkdir -p ${PACKAGE}
    tar cf - -C ${SOURCE} | tar xf - -C ${PACKAGE}
}

_main ${@:-}
