#!/bin/sh

set -o nounset

packages() {
    find /package/unpackage/data/catalog -type f | sed "s#^/package/unpackage/data/catalog/##"
}

if test ${#} = 0
then
    packages;
else
    if packages | grep -q "^${1}\$"
    then
        exec /package/unpackage/data/catalog/${@}
    else
        printf "\"%s\" is not a recognized package" "${1}"
    fi
fi
