#!/bin/sh
# -*- mode: shell-script -*-

set -o nounset

test ${DEBUGGING:-'false'} = 'false' || set -o xtrace

ROOT=${ROOT:-''}
PACKAGE_ROOT=${PACKAGE_ROOT:-${ROOT}/package}
UNPKG=${UNPKG:-${PACKAGE_ROOT}/unpkg/any}
CONFIG=${CONFIG:-${UNPKG}/config}

. ${CONFIG}/unpkg

_error_package_not_found() {
    cat <<-EOF >&2
error: package not found: "${1:-}"

You can get a list of known packages by running unpkg with no arguments.

EOF
    exit 100
}

_avail() {
    find "${CATALOG}/" -type f | tr -s / | sed "s#^${CATALOG}/##" | sort
}

_list() {
    find "${PACKAGE_ROOT}/" -mindepth 1 -maxdepth 1 -type d -exec basename '{}' \; | sort
}

_install() {
    if _avail | grep -q "^${1:-}\$"
    then
        INCLUDE=${INCLUDE} exec ${CATALOG}/${@:-}
    else
        _error_package_not_found "${@:-}"
    fi
}

main() {
    case ${1:-'list'} in
        av|avail) _avail;;
        ls|list) _list;;
        in|install) _install "${@:-}";;
        *) _install "${@:-}";;
    esac
}

main ${@:-}
