#!/bin/sh

NAME=${NAME:-'bearssl'}
VERSION=${VERSION:-'0.3'}
ORIGIN_PATH=${ORIGIN_PATH='with-tags/bearssl'}

. ${INCLUDE}/functions

_install() {
    mkdir -p ${COMMAND_DIR} ${LIBRARY_DIR} ${TOOL_DIR}
    tar cf - -C ${BUILD}/build brssl | tar xf - -C ${COMMAND_DIR}
    tar cf - -C ${BUILD}/build libbearssl.a libbearssl.so | tar xf - -C ${LIBRARY_DIR}
    tar cf - -C ${BUILD}/build testcrypto testspeed testx509 | tar xf - -C ${TOOL_DIR}
}

_main ${@:-}
