#!/bin/sh

NAME=${NAME:-'execline'}
VERSION=${VERSION:-'2.2.0.0'}
TAG=${TAG:-v${VERSION}}
ORIGIN_PATH=${ORIGIN_PATH='skarnet/execline'}

. ${INCLUDE}/functions

_configure() {
    cd ${BUILD} || _abort

    ./configure \
        $(_configure_options) \
        --enable-absolute-paths \
        --enable-shared \
        --with-dynlib=/package/skalibs/library \
        --with-lib=/package/skalibs/library \
        --with-sysdeps=/package/skalibs/sysdeps \
        ${@:-}
}

_main ${@:-}
