#!/bin/sh

NAME=${NAME:-'gnu-autoconf'}
VERSION=${VERSION:-'2.69'}
TAG=${TAG:-v${VERSION}}

ORIGIN_PREFIX='git://'
ORIGIN_HOST=${ORIGIN_HOST:-'git.savannah.gnu.org'}
ORIGIN_PATH=${ORIGIN_PATH:-'autoconf.git'}

. ${INCLUDE}/functions

_main ${@:-}
