#!/bin/sh

NAME=${NAME:-'gnu-automake'}
VERSION=${VERSION:-'1.15'}
TAG=${TAG:-v${VERSION}}

ORIGIN_PATH=${ORIGIN_PATH:-'tar-mirror/gnu-automake'}

. ${INCLUDE}/functions

_supports_autoconf() {
    false
}

_main ${@:-}
