#!/bin/sh

NAME=${NAME:-'go'}
VERSION=${VERSION:-'1.8'}
TAG=${TAG:-go${VERSION}}

ORIGIN_HOST=${ORIGIN_HOST='go.googlesource.com'}
ORIGIN_PATH=${ORIGIN_PATH='go'}

. ${INCLUDE}/functions

PATH=${PACKAGE_ROOT}/go/command:${PATH}

_bootstrap() {
    GO=${GO:-$(command -v go)}

    test -n ${GO} || test ${VERSION} = '1.4.3' || env VERSION=1.4.3 unpkg go
}

_build() {
    cd ${SOURCE}/src || _abort

    GO=${GO:-$(command -v go)}

    if test -n "${GO}"
    then
        env \
            GOROOT_BOOTSTRAP=$(${GO} env GOROOT) \
            GOROOT_FINAL=${PACKAGE} \
            ${SOURCE}/src/make.bash
    else
        env \
            GOROOT_FINAL=${PACKAGE} \
            ${SOURCE}/src/make.bash
    fi
}

_install() {
    mkdir -p ${PACKAGE} || _abort
    tar cf - -C ${SOURCE} . | tar xf - -C ${PACKAGE} || _abort
    mkdir -p ${BINDIR} || _abort
    ln -s ${PACKAGE}/bin/go ${BINDIR}/go
    ln -s ${PACKAGE}/bin/gofmt ${BINDIR}/gofmt
}

_main ${@:-}
