#!/bin/sh

NAME=${NAME:-'heirloom-sh'}
VERSION=${VERSION:-'master'}
ORIGIN_PATH=${ORIGIN_PATH='eunuchs/heirloom-project'}

. ${INCLUDE}/functions

_configure() {
    test -n "${AWK}" || _abort

    cd ${SOURCE}/heirloom/heirloom-sh || _abort

    ${AWK} -f ${UNPKG}/support/heirloom-sh/configure.awk \
        -F = \
        -v BINDIR=${BINDIR} \
        -v MANDIR=${MANDIR} \
        -v INSTALL=${INSTALL} \
        -v STRIP=${STRIP} \
        -v CFLAGS="${CFLAGS}" \
        makefile > makefile.fixed && mv makefile.fixed makefile
}

_import() {
    true
}

_main ${@:-}
