#!/bin/sh

NAME=${NAME:-'libarchive'}
VERSION=${VERSION:-'3.3.1'}
TAG=${TAG:-v${VERSION}}
ORIGIN_PATH=${ORIGIN_PATH='tar-mirror/libarchive'}

. ${INCLUDE}/functions

_supports_autoconf() {
    false
}

_main ${@:-}
