#!/bin/sh

NAME=${NAME:-'libressl'}
VERSION=${VERSION:-'2.5.1'}
TAG=${TAG:-v${VERSION}}
ORIGIN_PATH=${ORIGIN_PATH='libressl-portable/portable'}

. ${INCLUDE}/functions

_patch() {
    for patch in ${PATCHES}/${NAME} ${PATCHES}/${NAME}.$(uname -s)
    do
        if test -f ${patch}
        then
            git apply ${patch} || _abort
        fi
    done

    cat <<-EOF>${BUILD}/OPENBSD_BRANCH
libressl-${TAG}
EOF
}

_main ${@:-}
