#!/bin/sh

NAME=${NAME:-'lz4'}
VERSION=${VERSION:-'1.7.5'}
TAG=${TAG:-v${VERSION}}
ORIGIN_PATH=${ORIGIN_PATH='lz4/lz4'}

. ${INCLUDE}/functions

_build() {
    _clean && _make -C lib && _make -C programs
}

_install() {
    mkdir -p ${COMMAND_DIR} ${LIBRARY_DIR} ${INCLUDE_DIR} ${MANUAL_DIR}/man1 \
        && _make -C lib install \
        && _make -C programs install \
        && mv ${MANUAL_DIR}/*.1 ${MANUAL_DIR}/man1
}

_main ${@:-}
