#!/bin/sh

NAME=${NAME:-'mawk'}
VERSION=${VERSION:-'1.9.9.6'}
ORIGIN_PATH=${ORIGIN_PATH:-'ploxiln/mawk-2'}

. ${INCLUDE}/functions

_configure() {
    cd ${SOURCE} || _abort

    if test -x configure
    then
        ./configure \
            --prefix="${PREFIX}" \
            --bindir="${BINDIR}" \
            --libdir="${LIBDIR}" \
            --includedir="${INCLUDEDIR}" \
            --mandir="${MANDIR}" \
            CFLAGS="${CFLAGS}" \
            LDFLAGS="${LDFLAGS}"
        awk "\$1 == \"MANDIR\" { \$3 = \"${MANDIR}\" } \$1 == \"BINDIR\" { \$3 = \"${BINDIR}\" } { print }" Makefile > Makefile.fixed
        mv Makefile.fixed Makefile
    fi
}

_install() {
    mkdir -p ${COMMAND_DIR} ${MANUAL_DIR}/man1
    _make install
    mv ${MANUAL_DIR}/*.1 ${MANUAL_DIR}/man1
}

_main ${@:-}
