#!/bin/sh

NAME=${NAME:-'s6'}
VERSION=${VERSION:-'2.4.0.0'}
TAG=${TAG:-v${VERSION}}
ORIGIN_PREFIX=${ORIGIN_PREFIX:-'git://'}
ORIGIN_HOST=${ORIGIN_HOST:-'git.skarnet.org'}
ORIGIN_PATH=${ORIGIN_PATH='s6'}

. ${INCLUDE}/functions

_configure() {
    cd ${BUILD} || _abort

    ./configure \
        $(_configure_options) \
        --enable-absolute-paths \
        --enable-shared \
        --with-dynlib=/package/execline/library \
        --with-dynlib=/package/skalibs/library \
        --with-include=/package/execline/include \
        --with-include=/package/skalibs/include \
        --with-lib=/package/execline/library \
        --with-lib=/package/skalibs/library \
        --with-sysdeps=/package/skalibs/sysdeps \
        ${@:-}
}

_main ${@:-}
