#!/bin/sh

NAME=${NAME:-'s6-portable-utils'}
VERSION=${VERSION:-'2.1.0.0'}
TAG=${TAG:-v${VERSION}}
ORIGIN_PATH=${ORIGIN_PATH='skarnet/s6-portable-utils'}

. ${INCLUDE}/functions

_configure() {
    cd ${SOURCE} || _abort

    ./configure \
        $(_configure_options) \
        --enable-absolute-paths \
        --enable-shared \
        --with-dynlib=/package/skalibs/library \
        --with-include=/include \
        --with-lib=/package/skalibs/library \
        --with-sysdeps=/package/skalibs/sysdeps \
        ${@:-}
}

_main ${@:-}
