#!/bin/sh

NAME=${NAME:-'s6-rc'}
VERSION=${VERSION:-'0.1.0.0'}
TAG=${TAG:-v${VERSION}}
ORIGIN_PREFIX=${ORIGIN_PREFIX:-'git://'}
ORIGIN_HOST=${ORIGIN_HOST:-'git.skarnet.org'}
ORIGIN_PATH=${ORIGIN_PATH='s6-rc'}

. ${INCLUDE}/functions

_configure() {
    cd ${BUILD} || _abort

    ./configure \
        $(_configure_options) \
        --enable-absolute-paths \
        --enable-shared \
        --with-dynlib=/package/execline/any/library \
        --with-dynlib=/package/s6/any/library \
        --with-dynlib=/package/skalibs/any/library \
        --with-include=/package/execline/any/include \
        --with-include=/package/s6/any/include \
        --with-include=/package/skalibs/any/include \
        --with-lib=/package/execline/any/library \
        --with-lib=/package/s6/any/library \
        --with-lib=/package/skalibs/any/library \
        --with-sysdeps=/package/skalibs/any/sysdeps \
        ${@:-}
}

_main ${@:-}
