#!/bin/sh

NAME=${NAME:-'skalibs'}
VERSION=${VERSION:-'2.4.0.2'}
TAG=${TAG:-v${VERSION}}
ORIGIN_PREFIX=${ORIGIN_PREFIX:-'git://'}
ORIGIN_HOST=${ORIGIN_HOST:-'git.skarnet.org'}
ORIGIN_PATH=${ORIGIN_PATH='skalibs'}

. ${INCLUDE}/functions

_configure() {
    cd ${BUILD} || _abort

    ./configure \
        $(_configure_options) \
        --enable-absolute-paths \
        --enable-clock \
        --enable-iopause-select \
        --enable-monotonic \
        --with-default-path=${COMMAND_ROOT} \
        ${@:-}
}

_main ${@:-}
