#!/bin/sh

NAME=${NAME:-'xz-embedded'}
VERSION=${VERSION:-'master'}

ORIGIN_PREFIX=${ORIGIN_PREFIX='http://'}
ORIGIN_HOST=${ORIGIN_HOST='git.tukaani.org'}
ORIGIN_PATH=${ORIGIN_PATH='xz-embedded.git'}

. ${INCLUDE}/functions

BUILD=${SOURCE}/userspace

LDFLAGS=''

_install() {
    cd ${BUILD} || _abort

    mkdir -p ${COMMAND_DIR} ${INTERNAL_COMMAND_DIR}

    tar cf - xzminidec | tar xf - -C ${COMMAND_DIR}
    tar cf - boottest buftest bytetest | tar xf - -C ${INTERNAL_COMMAND_DIR}
}

_main ${@:-}
